### ISSUE TITLE
Please could you add a LICENSE file?

### ISSUE THREAD

**Issue by 12joan** [rockettomatooo/slate-react-presentation#15]
Hello,

I noticed that this GitHub repo is lacking a LICENSE file, even though the `package.json` file states that the intended license is MIT. The `package.json` field alone is [usually regarded as insufficient](https://opensource.stackexchange.com/a/7244) to grant an actual license.

Would you be able to add a LICENSE file to match the `package.json`?

**Comment by rockettomatooo** [comment]
@12joan thanks for your suggestion. Just added it and published `v0.2.1`.
