### ISSUE TITLE
Newlines are not rendered

### ISSUE THREAD

**Issue by agramian** [rockettomatooo/slate-react-presentation#9]
Is there anything in particular that needs to be done in order for newlines to be rendered?

**Comment by rockettomatooo** [comment]
@agramian how do your newlines look like within the document? is it just `\n` within text nodes?

**Comment by agramian** [comment]
@rockettomatooo I'll try to clarify as much as possible.

I'm using the official Slate [rich text example](https://github.com/ianstormtaylor/slate/blob/main/site/examples/richtext.tsx) and blank lines are not showing up when using your package.

The Slate `value` is:
```
[{"type":"paragraph","children":[{"text":"before blank line","code":true}]},{"type":"paragraph","children":[{"text":"","code":true}]},{"type":"paragraph","children":[{"text":"after blank line","code":true}]}]
```

And what that gets rendered as using Slate is:
```
<div data-gramm="false" role="textbox" spellcheck="true" data-slate-editor="true" data-slate-node="value" contenteditable="true" zindex="-1" style="position: relative; outline: none; white-space: pre-wrap; overflow-wrap: break-word;">
  <p data-slate-node="element"><span data-slate-node="text"><span data-slate-leaf="true"><code><span data-slate-string="true">before blank line</span></code></span></span></p>
  <p data-slate-node="element"><span data-slate-node="text"><span data-slate-leaf="true"><code><span data-slate-zero-width="n" data-slate-length="0">﻿<br></span></code></span></span></p>
  <p data-slate-node="element"><span data-slate-node="text"><span data-slate-leaf="true"><code><span data-slate-string="true">after blank line</span></code></span></span></p>
</div>
```

Using your package it gets rendered as:
```
<p><span><code><span>before blank line</span></code></span></p>
<p><span><code><span></span></code></span></p>
<p><span><code><span>after blank line</span></code></span></p>
```

Let me know if you need more info.

**Comment by rockettomatooo** [comment]
@agramian Okay I understand what you're saying now thanks!

So as far as I understand `slate-react`, it detects if a leaf is empty (and its parent too) so it'll render a zero-width space and also somehow detects if its a line break and adds the `<br />` ([source](https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/string.tsx)).
So on top of my head, I'm not exactly sure how I'd implement this behaviour here in this package. We'll probably have to somehow replicate the zero-width-space and linebreak detection. Unfortunately, I'm kinda busy right now so I'm not sure when I'll get to this. 
Can you maybe create a proposal pr or something? If not I'll see what I can do whenever I get to it. 

Also, as a out-of-package workaround: `renderLeaf` gets the `text` passed so you could also work around this issue by rendering a `<br />` yourself.
```
const { text } = renderLeafProps
{text === '' && <br />}
```

**Comment by maral** [comment]
In my case what helped is to just replace the text with a zero-width space character ('﻿' or `&#xFEFF;`) - the slate editor puts the same character there as well. Not sure when would the line break be inserted. It's possible it was relevant in an old version of slate.

The reason the zero-width space character works is that whenever a `div` or `p` is empty, it has its height set to zero. So there has to be something that prevents this, such as a non-breaking space or this strange zero-width space.

In your code, it's enough to replace this line:

```tsx
{renderLeaf?.({ attributes: {} as any, children: <LeafWrapper>{leaf.text}</LeafWrapper>, leaf, text: leaf })}
```

with this:
```tsx
{renderLeaf?.({ attributes: {} as any, children: <LeafWrapper>{leaf.text === '' ? '\uFEFF' : leaf.text}</LeafWrapper>, leaf, text: leaf })}
```
